logs:
  - name: root
    level: debug
    appenders:
      - type: FileLogAppender
        path: /home/szy/code/IM/IM_B/bin/log/root/root.log
        rotate_type: hour
      - type: StdoutLogAppender
        
  - name: system
    level: info
    appenders:
      - type: FileLogAppender
        path: /home/szy/code/IM/IM_B/bin/log/system/system.log
        rotate_type: size
        max_size: 10485760
      - type: StdoutLogAppender