logs:
  - name: root
    level: info
    formatter: '%d%T%t%T%N%T%F%T[%p]%T[%c]%T%f:%l%T%m%n'
    appender:
      - type: FileLogAppender
        file: log/svc_media/root.log
      - type: StdoutLogAppender

  - name: system
    level: info
    formatter: '%d%T%t%T%N%T%F%T[%p]%T[%c]%T%f:%l%T%m%n'
    appender:
      - type: FileLogAppender
        file: log/svc_media/system.log
      - type: StdoutLogAppender
